### ISSUE TITLE
Support for    configuring the NonMasqRule rule with specifying a source IP

### ISSUE THREAD

**Issue by biakecw** [Azure/ip-masq-agent-v2#52]
When using AKS (Azure Kubernetes Service) for VMSS (Virtual Machine Scale Sets) and associating multiple secondary network interfaces with multiple public IPs, I want the traffic from the secondary interfaces to be routed out through the associated public IPs.

   func writeNonMasqRule(lines *bytes.Buffer, cidr string) {
	writeRule(lines, utiliptables.Append, masqChain, nonMasqRuleComment, "-d", cidr, "-j", "RETURN")
}

 I   can only  specify the destination CIDR

**Comment by wedaly** [comment]
hi @biakecw could you please open an issue in https://github.com/azure/aks for this feature request?
